# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-09 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ovp_core', '0009_cause_image'),
        ('ovp_core', '0009_lead_date'),
    ]

    operations = [
    ]
