# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-14 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovp_core', '0012_simpleaddress_supplement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleaddress',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='simpleaddress',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='simpleaddress',
            name='neighbourhood',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='simpleaddress',
            name='number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='simpleaddress',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='simpleaddress',
            name='street',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='simpleaddress',
            name='supplement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='simpleaddress',
            name='zipcode',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CEP'),
        ),
    ]
